Added getHorizontalAlignment and getVerticalAlignment
dubstar-04/Design-Core pull request #65
Opened 2023-02-15 22:40 UTC by Brett-Parker

Test for entity text.js

Functions tested;

getHorizontalAlignment()
getVerticalAlignment()

2023-02-15 22:41 UTC, Brett-Parker commented
@dubstar-04 can you give this an eyeball before I add any other functions to the test.

2023-02-16 07:40 UTC, dubstar-04 commented
> @dubstar-04 can you give this an eyeball before I add any other functions to the test.

Looks good thanks.

2023-02-16 14:52 UTC, Brett-Parker commented
@dubstar-04 this is can be merged now. I haven't done;

width()
draw()
dxf()
snaps()
within()
touched()

These are often interaction based so harder to test but will review in future.

2023-02-20 16:34 UTC, dubstar-04 requested changes
The boundingbox of the Text entity currently can't be calculated without a valid canvas context. I'm aware of a practical way to solve this. 

An objects string representation may change causing these tests to fail even when the property of the object may be valid. Note the object string contains long floats in some cases and these may change for different architectures, so it's more better to test a fixed number of decimal places using .toBeCloseTo() https://jestjs.io/docs/expect#tobeclosetonumber-numdigits

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +  const expectedResult2 = {'height': 0, 'width': 0, 'x': 10, 'y': 10};
BoundingBox can't be calculated without a canvas context.

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +  const expectedResult = [{'type': 'Point', 'x': 10, 'y': 10}, 7.0710678118654755];
This is testing the objects string representation. It should test the objects property value. i.e. testPoint.x and testPoint.y

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +  const expectedResult2 = [{'type': 'Point', 'x': 10, 'y': 10}, 11.180339887498949];
This is testing the objects string representation.

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +  const expectedResult3 = [{'type': 'Point', 'x': 10, 'y': 10}, 14.142135623730951];
This is testing the objects string representation.

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +test('Test Text.extremes', () => {
This can't be tested without a valid boundingbox. see earlier comment.

2023-02-20 16:34 UTC, dubstar-04 commented on test/entities/text.test.js
> +test('Test Text.intersectPoints', () => {
This can't be tested without a valid boundingbox. see earlier comment.

2023-05-11 16:14 UTC, closed without merging